server.name: kibana
server.host: "0.0.0.0"

elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

xpack.security.enabled: true
xpack.monitoring.enabled: true
xpack.reporting.enabled: true

telemetry.enabled: false